//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resource.rc
//
#define IDD_DIALOG1                     103
//#define IDOK                            1001
//#define IDCANCEL                        1002
#define IDC_APPLY                       9395
#define IDD_TRIPARTITE_GRID_UNITS_DLG	679 
#define IDC_TRIPARTITE_HELP_BUTTIN      4354
#define IDC_TRIPARTITE_45_DEG_A_VALUE   4355
#define IDC_TRIPARTITE_135_DEG_B_VALUE  4356
#define IDC_TRIPARTITE_45_DEG_LABEL     4357
#define IDC_TRIPARTITE_135_DEG_LABEL    4358
#define IDC_TRIPARTITE_NUMBER_OF_MINOR_GRIDS 4359
#define IDC_TRIPARTITE_SELECT_UNITS_A   4360
#define IDC_TRIPARTITE_SELECT_UNITS_B   4361
#define IDC_TRIPARTITE_SELECT_UNITS_C   4362
#define IDC_TRIPARTITE_SELECT_UNITS_D   4363
#define IDC_TRIPARTITE_SELECT_UNITS_E   4364
#define IDC_TRIPARTITE_SELECT_UNITS_F   4365
#define IDC_TRIPARTITE_SELECT_UNITS_G   4366
#define IDC_TRIPARTITE_SELECT_UNITS_H   4367
#define IDC_TRIPARTITE_SELECT_UNITS_I   4368
#define IDC_TRIPARTITE_SELECT_UNITS_J   4369
#define IDC_TRIPARTITE_SELECT_UNITS_USER_DEFINED 4370
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
